/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreatePost: typeof import('./components/CreatePost.vue')['default']
    PostForm: typeof import('./components/PostForm.vue')['default']
    PostsList: typeof import('./components/PostsList.vue')['default']
  }
}
