/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CreatePost: typeof import('./components/CreatePost.vue')['default']
    ExampleComponent: typeof import('./components/ExampleComponent.vue')['default']
  }
}
